### ISSUE TITLE
IPython is required package to execute pytests

### ISSUE THREAD

**Issue by kevScheuer** [lan13005/PyAmpTools#7]
One of the last steps in the documentation is to execute `pytest -v`, which will throw the following error for multiple files:
`ModuleNotFoundError: No module named 'IPython'`

Executing `pip install IPython` fixes this issue. I would push this an edit myself but I'm unsure which setup script to modify to include this package

**Comment by lan13005** [comment]
Looks like Kevin fixed this in commit 60f61c5.
